server:
  port: 8081
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/postgresdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver