START TRANSACTION;
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('01','Guadeloupe','GUADELOUPE','97105');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('02','Martinique','MARTINIQUE','97209');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('03','Guyane','GUYANE','97302');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('04','La Réunion','LA REUNION','97411');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('06','Mayotte','MAYOTTE','97608');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('11','Île-de-France','ILE-DE-FRANCE','75056');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('21','Champagne-Ardenne','CHAMPAGNE-ARDENNE','51108');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('22','Picardie','PICARDIE','80021');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('23','Haute-Normandie','HAUTE-NORMANDIE','76540');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('24','Centre','CENTRE','45234');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('25','Basse-Normandie','BASSE-NORMANDIE','14118');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('26','Bourgogne','BOURGOGNE','21231');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('31','Nord-Pas-de-Calais','NORD-PAS-DE-CALAIS','59350');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('41','Lorraine','LORRAINE','57463');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('42','Alsace','ALSACE','67482');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('43','Franche-Comté','FRANCHE-COMTE','25056');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('52','Pays de la Loire','PAYS DE LA LOIRE','44109');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('53','Bretagne','BRETAGNE','35238');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('54','Poitou-Charentes','POITOU-CHARENTES','86194');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('72','Aquitaine','AQUITAINE','33063');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('73','Midi-Pyrénées','MIDI-PYRENEES','31555');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('74','Limousin','LIMOUSIN','87085');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('82','Rhône-Alpes','RHONE-ALPES','69123');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('83','Auvergne','AUVERGNE','63113');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('91','Languedoc-Roussillon','LANGUEDOC-ROUSSILLON','34172');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('93','Provence-Alpes-Côte d''Azur','PROVENCE-ALPES-COTE D''AZUR','13055');
insert into region(region_inseeid, name, name_uppercase, cheflieu_inseeid) VALUES ('94','Corse','CORSE','2A004');
COMMIT;
END TRANSACTION;
