version: '3'
services:
  db-people:
    build:
      context: ./db-people/
    image: shipstone/glowroot-demo-people-db:1.0
    container_name: people-db
    ports:
      - 5432:5432
  db-insee:
    build:
      context: ./db-insee/
    image: shipstone/glowroot-demo-insee-db:1.0
    container_name: insee-db
    ports:
      - 5433:5432
  db-cassandra:
    image: cassandra:3.11
    container_name: cassandra-db-glowroot
  glowroot:
    image: glowroot/glowroot-central:0.11.1
    container_name: glowroot-0.11.1
    ports:
      - 4000:4000
      - 8181:8181
    links:
      - db-cassandra:cassandra

